[project]
name = "image-converter"
version = "1.5.1"
description = ""
authors = [
    {name = "Alejrot"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pillow (>=11.2.1,<12.0.0)",
    "rich (>=14.0.0,<15.0.0)",
    "python-i18n[yaml] (>=0.3.9,<0.4.0)"
]

[tool.poetry]
packages = [
    {include = "src"}
    ]


[tool.poetry.group.test.dependencies]
ruff = "^0.11.12"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"



[project.scripts]
img-convert = "src:main"
